/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionidRouteImport } from './routes/sessions.$sessionid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const SessionsSessionidRoute = SessionsSessionidRouteImport.update({
  id: '/sessions/$sessionid',
  path: '/sessions/$sessionid',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsSessionidRoute: SessionsSessionidRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
