/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomcodeRouteImport } from './routes/rooms.$roomcode'
import { Route as RoomsRoomcodeGamesGameidPlayRouteImport } from './routes/rooms.$roomcode.games.$gameid.play'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const RoomsRoomcodeRoute = RoomsRoomcodeRouteImport.update({
  id: '/rooms/$roomcode',
  path: '/rooms/$roomcode',
  getParentRoute: () => rootRouteImport,
})
const RoomsRoomcodeGamesGameidPlayRoute =
  RoomsRoomcodeGamesGameidPlayRouteImport.update({
    id: '/games/$gameid/play',
    path: '/games/$gameid/play',
    getParentRoute: () => RoomsRoomcodeRoute,
  })

const RoomsRoomcodeRouteChildren = {
  RoomsRoomcodeGamesGameidPlayRoute: RoomsRoomcodeGamesGameidPlayRoute,
}

const RoomsRoomcodeRouteWithChildren = RoomsRoomcodeRoute._addFileChildren(
  RoomsRoomcodeRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RoomsRoomcodeRoute: RoomsRoomcodeRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
